### ISSUE TITLE
CSV column parsers

### ISSUE THREAD

**Issue by moonthug** [kiln/flourish-sdk#27]
At the moment all CSV data is added to the main `data` object as a string. The means that you either have to convert them all to ints, floats etc or when you need to use them.

It would be great if you could specify a column or column range formatter.

Straight forward parseInt-ing.
```yaml
  - dataset: growthBoundsColorMap
    key: from
    name: From
    type: column
    column: lookup_growth_bounds_color::A
    parser: parseInt
```

Custom functions that can be specified in the template.

```yaml
  - dataset: growthBoundsColorMap
    key: to
    name: To
    type: column
    column: lookup_growth_bounds_color::B
    parser: hexToHSL
```

Chaining parsers together with arguments
```yaml
  - dataset: growthBoundsColorMap
    key: color
    name: Color
    type: column
    column: lookup_growth_bounds_color::C
    parser:
      - hexToHSL
      - shiftHue
        - 10
      - darken
```
