### ISSUE TITLE
`flourish upgrade` to v3 issues with template.yml

### ISSUE THREAD

**Issue by theduncanclark** [kiln/flourish-sdk#42]
I think this happened as a result of running Flourish upgrade:

![image](https://user-images.githubusercontent.com/9587433/39837212-b7a4c7e4-53cd-11e8-92ed-341c9e437131.png)

Two issues:

1) It removes comments for no apparent good reason
2) It changes array styles into (in my view less legible) non-square-bracket format

**Comment by robinhouston** [comment]
Interesting! Fixing this completely would require developing a new YAML parser, I think, since [js-yaml](https://github.com/nodeca/js-yaml) doesn’t retain any information about comments or formatting when it parses the document.

It may be possible to use the `flowLevel` option to make the arrays come out in a way that is more to your taste, though. I’ll experiment with it.

**Comment by robinhouston** [comment]
If we set `flowLevel: 4` then it comes out like this:

```yaml
  - property: palette
    name: Colour scheme or custom colours
    description: >-
      Choose from the list or enter a custom palette as a comma-separated list
      of colour codes or names (e.g. red, #343434)
    type: string
    choices:
      - [Flourish categories A, flourish_default_1]
      - [Flourish categories B, flourish_default_2]
      - [Pastel light, carto_pastel]
      - [Pastel dark, carto_antique]
      - [Rainbow, carto_rainbow]
      - [20 colours (paired), schemeCategory20]
```

Better?
