### ISSUE TITLE
Unable to use `show_if` on imported settings

### ISSUE THREAD

**Issue by hughsk** [kiln/flourish-sdk#47]
The following code in settings:

``` yml
- property: arc.palette
  show_if: arc.arc_palette_color
  import: "@flourish/custom-colors"
```

Leads to this error:

```
😱  Failed to reload template
😱  template.yml: Unexpected property 'show_if' in import
```

Unsure if I'm going to end up using it this way this time, but it might be useful in some cases?
