### ISSUE TITLE
Conditional settings based on data bindings do not work in the SDK

### ISSUE THREAD

**Issue by theduncanclark** [kiln/flourish-sdk#49]
For example if a setting has…

`show_if: data.my_binding`

… the setting will never show up in the SDK, whereas in the main app the setting will show and hide as designed, based on whether the binding is set.

**Comment by theduncanclark** [comment]
I'd like to bump this as it continues to be very frustrating when developing templates.

**Comment by animateddata** [comment]
I've just encountered this one again too!

**Comment by peterrcook-canva** [comment]
Conditions such as:

```
data.points.value: true
```

seem to work ok in the SDK, but ones based on data types such as:

```
data.choropleth.value.type: number
```

work in the main app, but not the SDK.

**Comment by peterrcook-canva** [comment]
Another related case that works in published templates, but not the SDK is:

```
    overrides:
      - tag: discrete
        method: extend
        show_if:
          data.data.color.type: string
      - tag: numeric
        method: extend
        show_if:
          data.data.color.type: number
```

**Comment by maartenzam** [comment]
I also ran into this.

On a side note: Peter's example above uses "number" to check the binding type, but in the [conditional settings section of the docs](https://developers.flourish.studio/sdk/api-reference/template-yml/#conditional-settings), it's "numeric":

```
show_if:
  - chart_mode: line
  - chart_mode: bar
    data.data.labels.type: **numeric**
```
