### ISSUE TITLE
SDK doesn't respect data_type, hints in template.yml

### ISSUE THREAD

**Issue by aendrew** [kiln/flourish-sdk#80]
I have a dataset that has a column that is mostly numbers, but a few values like `2A`. I need to ensure this is a string, but the SDK keeps typing it as a number (and losing any alphabetical designations in the process, thus breaking the IDs). I've tried configuring it in template.yml a few ways, up to:

```
  - key: code
    name: Code
    dataset: geography
    type: column
    column: france_departments::B
    data_type: string
    assignment:
      hints:
        string: true  # This default can be omitted.
        number: false # This stops number columns being picked.
```

No matter how explicit I am, the SDK seems to ignore the data_type setting.
