### ISSUE TITLE
Conditional settings seems not to work

### ISSUE THREAD

**Issue by ilariaventurini** [kiln/flourish-sdk#85]
Hello, I'm creating a Flourish template using Flourish SDK and I tried to use [conditional settings](https://developers.flourish.studio/sdk/api-reference/template-yml/#conditional-settings) in this way:

```yml
  - property: show_test_label
    name: Show test label
    type: boolean

  - property: test_label
    name: Test label
    type: string
    show_if:
      show_test_label: true
```

The problem is that the input string `test_label` is always visible, whether show_test_label is `true` or `false`.

![Nov-07-2022 08-39-23](https://user-images.githubusercontent.com/44204353/200252803-9853a5c1-0bb1-459d-9577-d39ed1ed255d.gif)

I tried also `hide_if` but the result is the same. Is that a bug or am I missing something?

Thanks
